---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: networkautomation
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: networkautomation
    creationPolicy: Owner

  data:
    - secretKey: MICROSOFT_AUTH_CLIENT_ID
      remoteRef:
        key: kv/networkautomation
        property: MICROSOFT_AUTH_CLIENT_ID
